### ISSUE TITLE
LAB1 Familliar with gem5 中的 Malloc and Free LAB 实验在执行前需要重新编译 gem5

### ISSUE THREAD

**Issue by huangcb01** [arcsysu/SYSU-ARCH#1]
# LAB1 Familliar with gem5 中的 Malloc and Free LAB 实验在执行前需要重新编译 gem5

## 问题

我按照教程操作，到了执行的时候报错称无效的 debug 标志“MemAlloc”：

```
$ ~/gem5/build/X86/gem5.opt --debug-flags=MemAlloc ./SYSU-ARCH/assets/LAB1/arch-sysu/MemAlloc.py
gem5 Simulator System.  https://www.gem5.org     
gem5 is copyrighted software; use the --copyright option for details.

gem5 version 22.0.0.2
gem5 compiled Oct 22 2022 00:39:20
gem5 started Oct 22 2022 10:57:51
gem5 executing on OnewayPC, pid 20319
command line: /home/oneway/gem5/build/X86/gem5.opt --debug-flags=MemAlloc ./SYSU-ARCH/assets/LAB1/arch-sysu/MemAlloc.py

invalid debug flag 'MemAlloc'
```

## 解决

查阅 [官方教程](https://www.gem5.org/documentation/learning_gem5/part2/helloobject/) 得知创建 SimObject 需要重新编译 gem5，重新编译之后再执行就好了。

## 建议

在实验文档中加上重新编译这一步。另外，建议加入提示，编译 gem5 时可加入参数  -j<cores+1> 加快编译速度。

**Comment by gty111** [comment]
感谢issue（而不是qq私聊）
### 编译 gem5 时可加入参数 -j<cores+1> 加快编译速度
-j 参数在实验文档中有写
<img width="584" alt="image" src="https://user-images.githubusercontent.com/51089307/197921242-1ebc9db8-9191-4d09-9fe3-688436915106.png">
### 在实验文档中加上重新编译这一步
已添加提示在 https://arcsysu.github.io/SYSU-ARCH/docs/LAB1/Malloc%20and%20Free%20LAB.html
When to rebuild gem5
gem5 has config files like `.py` and `SConscript` . Some config files will influence gem5 binary(ELF file). 
Some config files just influence gem5 runtime behavior. You need to distinguish that by yourself.
For example, if you add some new features to gem5, rebuilding gem5 is obivous.
