### ISSUE TITLE
无法生成config.pdf、config.svg？

### ISSUE THREAD

**Issue by ttdxx7023** [arcsysu/SYSU-ARCH#10]
环境：wsl+Ubuntu20.04、python版本3.8.10
尝试过用pip3安装pydot-1.4.2、pyparsing>=2.1.4和用pip3安装pydot2，均无法解决问题

**Comment by yhgu2000** [comment]
这两个需要用pip安装额外的包才会生成，不安装的话不会影响结果的正确性

具体安装什么包可以留意编译gem5时给出的warning信息
