### ISSUE TITLE
lab1 build and simulate 修改cpu model

### ISSUE THREAD

**Issue by Msyu1020** [arcsysu/SYSU-ARCH#2]
根据教程找到了X86CPU.py，并且仿照该文件写了以下语句
```
//隐藏代码
```
但是在仿真运行的时候提示
se.py: error: argument --cpu-type: invalid choice: 'X86MinorCPU' (choose from 'AtomicSimpleCPU', 'BaseAtomicSimpleCPU', 'BaseMinorCPU', 'BaseNonCachingSimpleCPU', 'BaseO3CPU', 'BaseTimingSimpleCPU', 'DerivO3CPU', 'NonCachingSimpleCPU', 'O3CPU', 'TimingSimpleCPU', 'TraceCPU', 'X86AtomicSimpleCPU', 'X86KvmCPU', 'X86NonCachingSimpleCPU', 'X86O3CPU', 'X86TimingSimpleCPU')

在备选项里没有出现minorcpu，搜索后也没有找到如何更改CPU模式的方法

**Comment by gty111** [comment]
修改完重新编译gem5了吗

**Comment by Msyu1020** [comment]
重新编译完可以了，谢谢助教！ 

> 修改完重新编译gem5了吗
