### ISSUE TITLE
Lab 6 的 Build ACCEL-SIM 部分建议加入一些解释

### ISSUE THREAD

**Issue by DueDine** [arcsysu/SYSU-ARCH#5]
在执行以下两条指令时
`source ./gpu-simulator/setup_environment.sh`
`make -j -C ./gpu-simulator/`
可能会出现类似于
> nvcc fatal : Unsupported gpu architecture 'compute_10'

等看起来是错误的信息
但根据[链接](https://groups.google.com/g/accel-sim/c/HnUcDLalXXk) 以上错误是正常的 可以通过在指令中加入 `-i` 消除这些报错

**Comment by gty111** [comment]
我在运行
```
source ./gpu-simulator/setup_environment.sh
make -j -C ./gpu-simulator/
```
并没有发现出现错误

### 关于链接的问题
- 首先链接指出的问题不是accel-sim仿真器的，而是https://github.com/accel-sim/gpu-app-collection 里的问题
- 其次链接指出的问题是在运行`source ./gpu-app-collection/src/setup_environment` 会出现忽略的错误，也就是已经加上`-i`参数了
