### ISSUE TITLE
在Gem5上跑sieve时报错Syscall 334 out of range

### ISSUE THREAD

**Issue by 91Mrcui** [arcsysu/SYSU-ARCH#8]
执行命令：build/X86/gem5.opt configs/example/se.py --cmd=tests/test-progs/hello/bin/x86/linux/sieve --cpu-type=TimingSimpleCPU --l1d_size=64MB --l1i_size=16MB --caches

报错信息：build/X86/sim/syscall_emul.cc:74: warn: ignoring syscall set_robust_list(...)
build/X86/sim/syscall_desc.hh:209: fatal: Syscall 334 out of range

### 解决方法：
按助教所提供的链接 https://askubuntu.com/questions/1427882/syscall-issues-compiling-x86-c-code-for-gem5-using-ubuntu-22-04

**Comment by gty111** [comment]
是这个问题吗 https://askubuntu.com/questions/1427882/syscall-issues-compiling-x86-c-code-for-gem5-using-ubuntu-22-04

**Comment by 91Mrcui** [comment]
我试试，
按照上面的指导修改syscall_tbl64.cc后是不是还得重新编译gem5才能生效

**Comment by gty111** [comment]
对，需要重新编译
